add TLS support for REST
golangid/candi pull request #32
Opened 2023-11-21 05:50 UTC by isogram

- added new three env. USE_REST_TLS, REST_TLS_CERT_FILE, REST_TLS_KEY_FILE
- added logic to serve HTTPS for REST

2023-11-22 02:03 UTC, agungdwiprasetyo requested changes

2023-11-22 02:03 UTC, agungdwiprasetyo commented on codebase/app/rest_server/rest_server.go
> +
jadi ketika `Serve` cukup begini aja
```suggestion
func (s *restServer) Serve() {
	var err error

	if s.listener == nil {
		s.listener, err = net.Listen("tcp", s.httpEngine.Addr)
		if err != nil {
			log.Panicf("REST TCP Listener: Unexpected Error: %v", err)
		}
	}

	if s.opt.tlsConfig != nil {
		s.httpEngine.TLSConfig = s.opt.tlsConfig
		s.listener = tls.NewListener(s.listener, s.opt.tlsConfig)
	}

	err = s.httpEngine.Serve(s.listener)
	switch err.(type) {
	case *net.OpError:
		log.Panicf("REST Server: Unexpected Error: %v", err)
	}
}
```

2023-11-22 02:03 UTC, agungdwiprasetyo commented on config/env/environment.go
> +	UseRESTTls bool
dan jadi gaperlu ada tambahan default env

2023-11-22 02:03 UTC, agungdwiprasetyo commented on codebase/factory/appfactory/setup_rest_server.go
> +		restserver.SetTlsOption(env.BaseEnv().UseRESTTls),
jadi yg disini udah gaperlu, cukup lewat `configs/app_factory.go` dari sisi app-nya saja

(dari sisi app-nya)
```suggestion
		if env.BaseEnv().UseREST {
		apps = append(apps, appfactory.SetupRESTServer(service, restserver.SetTLSConfig(getTLSConfig())))
		...
```

2023-11-22 23:38 UTC, merged

2023-11-23 02:39 UTC, isogram commented
ok gue PR ke changesnya ke development yak @agungdwiprasetyo